

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


TRUNCATE TABLE `countries`;


INSERT INTO `countries` (`id`, `name`, `iso_code_2`, `iso_code_3`, `address_format`, `postcode_required`, `status`) VALUES
(1, '{\"en\":\"Afghanistan\"}', 'AF', 'AFG', '', 0, 1),
(2, '{\"en\":\"Albania\"}', 'AL', 'ALB', '', 0, 1),
(3, '{\"en\":\"Algeria\"}', 'DZ', 'DZA', '', 0, 1),
(4, '{\"en\":\"American Samoa\"}', 'AS', 'ASM', '', 0, 1),
(5, '{\"en\":\"Andorra\"}', 'AD', 'AND', '', 0, 1),
(6, '{\"en\":\"Angola\"}', 'AO', 'AGO', '', 0, 1),
(7, '{\"en\":\"Anguilla\"}', 'AI', 'AIA', '', 0, 1),
(8, '{\"en\":\"Antarctica\"}', 'AQ', 'ATA', '', 0, 1),
(9, '{\"en\":\"Antigua and Barbuda\"}', 'AG', 'ATG', '', 0, 1),
(10, '{\"en\":\"Argentina\"}', 'AR', 'ARG', '', 0, 1),
(11, '{\"en\":\"Armenia\"}', 'AM', 'ARM', '', 0, 1),
(12, '{\"en\":\"Aruba\"}', 'AW', 'ABW', '', 0, 1),
(13, '{\"en\":\"Australia\"}', 'AU', 'AUS', '', 0, 1),
(14, '{\"en\":\"Austria\"}', 'AT', 'AUT', '', 0, 1),
(15, '{\"en\":\"Azerbaijan\"}', 'AZ', 'AZE', '', 0, 1),
(16, '{\"en\":\"Bahamas\"}', 'BS', 'BHS', '', 0, 1),
(17, '{\"en\":\"Bahrain\"}', 'BH', 'BHR', '', 0, 1),
(18, '{\"en\":\"Bangladesh\"}', 'BD', 'BGD', '', 0, 1),
(19, '{\"en\":\"Barbados\"}', 'BB', 'BRB', '', 0, 1),
(20, '{\"en\":\"Belarus\"}', 'BY', 'BLR', '', 0, 1),
(21, '{\"en\":\"Belgium\"}', 'BE', 'BEL', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 0, 1),
(22, '{\"en\":\"Belize\"}', 'BZ', 'BLZ', '', 0, 1),
(23, '{\"en\":\"Benin\"}', 'BJ', 'BEN', '', 0, 1),
(24, '{\"en\":\"Bermuda\"}', 'BM', 'BMU', '', 0, 1),
(25, '{\"en\":\"Bhutan\"}', 'BT', 'BTN', '', 0, 1),
(26, '{\"en\":\"Bolivia\"}', 'BO', 'BOL', '', 0, 1),
(27, '{\"en\":\"Bosnia and Herzegovina\"}', 'BA', 'BIH', '', 0, 1),
(28, '{\"en\":\"Botswana\"}', 'BW', 'BWA', '', 0, 1),
(29, '{\"en\":\"Bouvet Island\"}', 'BV', 'BVT', '', 0, 1),
(30, '{\"en\":\"Brazil\"}', 'BR', 'BRA', '', 0, 1),
(31, '{\"en\":\"British Indian Ocean Territory\"}', 'IO', 'IOT', '', 0, 1),
(32, '{\"en\":\"Brunei Darussalam\"}', 'BN', 'BRN', '', 0, 1),
(33, '{\"en\":\"Bulgaria\"}', 'BG', 'BGR', '', 0, 1),
(34, '{\"en\":\"Burkina Faso\"}', 'BF', 'BFA', '', 0, 1),
(35, '{\"en\":\"Burundi\"}', 'BI', 'BDI', '', 0, 1),
(36, '{\"en\":\"Cambodia\"}', 'KH', 'KHM', '', 0, 1),
(37, '{\"en\":\"Cameroon\"}', 'CM', 'CMR', '', 0, 1),
(38, '{\"en\":\"Canada\"}', 'CA', 'CAN', '', 0, 1),
(39, '{\"en\":\"Cape Verde\"}', 'CV', 'CPV', '', 0, 1),
(40, '{\"en\":\"Cayman Islands\"}', 'KY', 'CYM', '', 0, 1),
(41, '{\"en\":\"Central African Republic\"}', 'CF', 'CAF', '', 0, 1),
(42, '{\"en\":\"Chad\"}', 'TD', 'TCD', '', 0, 1),
(43, '{\"en\":\"Chile\"}', 'CL', 'CHL', '', 0, 1),
(44, '{\"en\":\"China\"}', 'CN', 'CHN', '', 0, 1),
(45, '{\"en\":\"Christmas Island\"}', 'CX', 'CXR', '', 0, 1),
(46, '{\"en\":\"Cocos (Keeling) Islands\"}', 'CC', 'CCK', '', 0, 1),
(47, '{\"en\":\"Colombia\"}', 'CO', 'COL', '', 0, 1),
(48, '{\"en\":\"Comoros\"}', 'KM', 'COM', '', 0, 1),
(49, '{\"en\":\"Congo\"}', 'CG', 'COG', '', 0, 1),
(50, '{\"en\":\"Cook Islands\"}', 'CK', 'COK', '', 0, 1),
(51, '{\"en\":\"Costa Rica\"}', 'CR', 'CRI', '', 0, 1),
(52, '{\"en\":\"Cote D\'Ivoire\"}', 'CI', 'CIV', '', 0, 1),
(53, '{\"en\":\"Croatia\"}', 'HR', 'HRV', '', 0, 1),
(54, '{\"en\":\"Cuba\"}', 'CU', 'CUB', '', 0, 1),
(55, '{\"en\":\"Cyprus\"}', 'CY', 'CYP', '', 0, 1),
(56, '{\"en\":\"Czech Republic\"}', 'CZ', 'CZE', '', 0, 1),
(57, '{\"en\":\"Denmark\"}', 'DK', 'DNK', '', 0, 1),
(58, '{\"en\":\"Djibouti\"}', 'DJ', 'DJI', '', 0, 1),
(59, '{\"en\":\"Dominica\"}', 'DM', 'DMA', '', 0, 1),
(60, '{\"en\":\"Dominican Republic\"}', 'DO', 'DOM', '', 0, 1),
(61, '{\"en\":\"East Timor\"}', 'TL', 'TLS', '', 0, 1),
(62, '{\"en\":\"Ecuador\"}', 'EC', 'ECU', '', 0, 1),
(63, '{\"en\":\"Egypt\"}', 'EG', 'EGY', '', 0, 1),
(64, '{\"en\":\"El Salvador\"}', 'SV', 'SLV', '', 0, 1),
(65, '{\"en\":\"Equatorial Guinea\"}', 'GQ', 'GNQ', '', 0, 1),
(66, '{\"en\":\"Eritrea\"}', 'ER', 'ERI', '', 0, 1),
(67, '{\"en\":\"Estonia\"}', 'EE', 'EST', '', 0, 1),
(68, '{\"en\":\"Ethiopia\"}', 'ET', 'ETH', '', 0, 1),
(69, '{\"en\":\"Falkland Islands (Malvinas)\"}', 'FK', 'FLK', '', 0, 1),
(70, '{\"en\":\"Faroe Islands\"}', 'FO', 'FRO', '', 0, 1),
(71, '{\"en\":\"Fiji\"}', 'FJ', 'FJI', '', 0, 1),
(72, '{\"en\":\"Finland\"}', 'FI', 'FIN', '', 0, 1),
(74, '{\"en\":\"France, Metropolitan\"}', 'FR', 'FRA', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 1, 1),
(75, '{\"en\":\"French Guiana\"}', 'GF', 'GUF', '', 0, 1),
(76, '{\"en\":\"French Polynesia\"}', 'PF', 'PYF', '', 0, 1),
(77, '{\"en\":\"French Southern Territories\"}', 'TF', 'ATF', '', 0, 1),
(78, '{\"en\":\"Gabon\"}', 'GA', 'GAB', '', 0, 1),
(79, '{\"en\":\"Gambia\"}', 'GM', 'GMB', '', 0, 1),
(80, '{\"en\":\"Georgia\"}', 'GE', 'GEO', '', 0, 1),
(81, '{\"en\":\"Germany\"}', 'DE', 'DEU', '{company}\r\n{firstname} {lastname}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 1, 1),
(82, '{\"en\":\"Ghana\"}', 'GH', 'GHA', '', 0, 1),
(83, '{\"en\":\"Gibraltar\"}', 'GI', 'GIB', '', 0, 1),
(84, '{\"en\":\"Greece\"}', 'GR', 'GRC', '', 0, 1),
(85, '{\"en\":\"Greenland\"}', 'GL', 'GRL', '', 0, 1),
(86, '{\"en\":\"Grenada\"}', 'GD', 'GRD', '', 0, 1),
(87, '{\"en\":\"Guadeloupe\"}', 'GP', 'GLP', '', 0, 1),
(88, '{\"en\":\"Guam\"}', 'GU', 'GUM', '', 0, 1),
(89, '{\"en\":\"Guatemala\"}', 'GT', 'GTM', '', 0, 1),
(90, '{\"en\":\"Guinea\"}', 'GN', 'GIN', '', 0, 1),
(91, '{\"en\":\"Guinea-Bissau\"}', 'GW', 'GNB', '', 0, 1),
(92, '{\"en\":\"Guyana\"}', 'GY', 'GUY', '', 0, 1),
(93, '{\"en\":\"Haiti\"}', 'HT', 'HTI', '', 0, 1),
(94, '{\"en\":\"Heard and Mc Donald Islands\"}', 'HM', 'HMD', '', 0, 1),
(95, '{\"en\":\"Honduras\"}', 'HN', 'HND', '', 0, 1),
(96, '{\"en\":\"Hong Kong\"}', 'HK', 'HKG', '', 0, 1),
(97, '{\"en\":\"Hungary\"}', 'HU', 'HUN', '', 0, 1),
(98, '{\"en\":\"Iceland\"}', 'IS', 'ISL', '', 0, 1),
(99, '{\"en\":\"India\"}', 'IN', 'IND', '', 0, 1),
(100, '{\"en\":\"Indonesia\"}', 'ID', 'IDN', '', 0, 1),
(101, '{\"en\":\"Iran (Islamic Republic of)\"}', 'IR', 'IRN', '', 0, 1),
(102, '{\"en\":\"Iraq\"}', 'IQ', 'IRQ', '', 0, 1),
(103, '{\"en\":\"Ireland\"}', 'IE', 'IRL', '', 0, 1),
(104, '{\"en\":\"Israel\"}', 'IL', 'ISR', '', 0, 1),
(105, '{\"en\":\"Italy\"}', 'IT', 'ITA', '', 0, 1),
(106, '{\"en\":\"Jamaica\"}', 'JM', 'JAM', '', 0, 1),
(107, '{\"en\":\"Japan\"}', 'JP', 'JPN', '', 0, 1),
(108, '{\"en\":\"Jordan\"}', 'JO', 'JOR', '', 0, 1),
(109, '{\"en\":\"Kazakhstan\"}', 'KZ', 'KAZ', '', 0, 1),
(110, '{\"en\":\"Kenya\"}', 'KE', 'KEN', '', 0, 1),
(111, '{\"en\":\"Kiribati\"}', 'KI', 'KIR', '', 0, 1),
(112, '{\"en\":\"North Korea\"}', 'KP', 'PRK', '', 0, 1),
(113, '{\"en\":\"Korea, Republic of\"}', 'KR', 'KOR', '', 0, 1),
(114, '{\"en\":\"Kuwait\"}', 'KW', 'KWT', '', 0, 1),
(115, '{\"en\":\"Kyrgyzstan\"}', 'KG', 'KGZ', '', 0, 1),
(116, '{\"en\":\"Lao People\'s Democratic Republic\"}', 'LA', 'LAO', '', 0, 1),
(117, '{\"en\":\"Latvia\"}', 'LV', 'LVA', '', 0, 1),
(118, '{\"en\":\"Lebanon\"}', 'LB', 'LBN', '', 0, 1),
(119, '{\"en\":\"Lesotho\"}', 'LS', 'LSO', '', 0, 1),
(120, '{\"en\":\"Liberia\"}', 'LR', 'LBR', '', 0, 1),
(121, '{\"en\":\"Libyan Arab Jamahiriya\"}', 'LY', 'LBY', '', 0, 1),
(122, '{\"en\":\"Liechtenstein\"}', 'LI', 'LIE', '', 0, 1),
(123, '{\"en\":\"Lithuania\"}', 'LT', 'LTU', '', 0, 1),
(124, '{\"en\":\"Luxembourg\"}', 'LU', 'LUX', '', 0, 1),
(125, '{\"en\":\"Macau\"}', 'MO', 'MAC', '', 0, 1),
(126, '{\"en\":\"FYROM\"}', 'MK', 'MKD', '', 0, 1),
(127, '{\"en\":\"Madagascar\"}', 'MG', 'MDG', '', 0, 1),
(128, '{\"en\":\"Malawi\"}', 'MW', 'MWI', '', 0, 1),
(129, '{\"en\":\"Malaysia\"}', 'MY', 'MYS', '', 0, 1),
(130, '{\"en\":\"Maldives\"}', 'MV', 'MDV', '', 0, 1),
(131, '{\"en\":\"Mali\"}', 'ML', 'MLI', '', 0, 1),
(132, '{\"en\":\"Malta\"}', 'MT', 'MLT', '', 0, 1),
(133, '{\"en\":\"Marshall Islands\"}', 'MH', 'MHL', '', 0, 1),
(134, '{\"en\":\"Martinique\"}', 'MQ', 'MTQ', '', 0, 1),
(135, '{\"en\":\"Mauritania\"}', 'MR', 'MRT', '', 0, 1),
(136, '{\"en\":\"Mauritius\"}', 'MU', 'MUS', '', 0, 1),
(137, '{\"en\":\"Mayotte\"}', 'YT', 'MYT', '', 0, 1),
(138, '{\"en\":\"Mexico\"}', 'MX', 'MEX', '', 0, 1),
(139, '{\"en\":\"Micronesia, Federated States of\"}', 'FM', 'FSM', '', 0, 1),
(140, '{\"en\":\"Moldova, Republic of\"}', 'MD', 'MDA', '', 0, 1),
(141, '{\"en\":\"Monaco\"}', 'MC', 'MCO', '', 0, 1),
(142, '{\"en\":\"Mongolia\"}', 'MN', 'MNG', '', 0, 1),
(143, '{\"en\":\"Montserrat\"}', 'MS', 'MSR', '', 0, 1),
(144, '{\"en\":\"Morocco\"}', 'MA', 'MAR', '', 0, 1),
(145, '{\"en\":\"Mozambique\"}', 'MZ', 'MOZ', '', 0, 1),
(146, '{\"en\":\"Myanmar\"}', 'MM', 'MMR', '', 0, 1),
(147, '{\"en\":\"Namibia\"}', 'NA', 'NAM', '', 0, 1),
(148, '{\"en\":\"Nauru\"}', 'NR', 'NRU', '', 0, 1),
(149, '{\"en\":\"Nepal\"}', 'NP', 'NPL', '', 0, 1),
(150, '{\"en\":\"Netherlands\"}', 'NL', 'NLD', '', 0, 1),
(151, '{\"en\":\"Netherlands Antilles\"}', 'AN', 'ANT', '', 0, 1),
(152, '{\"en\":\"New Caledonia\"}', 'NC', 'NCL', '', 0, 1),
(153, '{\"en\":\"New Zealand\"}', 'NZ', 'NZL', '', 0, 1),
(154, '{\"en\":\"Nicaragua\"}', 'NI', 'NIC', '', 0, 1),
(155, '{\"en\":\"Niger\"}', 'NE', 'NER', '', 0, 1),
(156, '{\"en\":\"Nigeria\"}', 'NG', 'NGA', '', 0, 1),
(157, '{\"en\":\"Niue\"}', 'NU', 'NIU', '', 0, 1),
(158, '{\"en\":\"Norfolk Island\"}', 'NF', 'NFK', '', 0, 1),
(159, '{\"en\":\"Northern Mariana Islands\"}', 'MP', 'MNP', '', 0, 1),
(160, '{\"en\":\"Norway\"}', 'NO', 'NOR', '', 0, 1),
(161, '{\"en\":\"Oman\"}', 'OM', 'OMN', '', 0, 1),
(162, '{\"en\":\"Pakistan\"}', 'PK', 'PAK', '', 0, 1),
(163, '{\"en\":\"Palau\"}', 'PW', 'PLW', '', 0, 1),
(164, '{\"en\":\"Panama\"}', 'PA', 'PAN', '', 0, 1),
(165, '{\"en\":\"Papua New Guinea\"}', 'PG', 'PNG', '', 0, 1),
(166, '{\"en\":\"Paraguay\"}', 'PY', 'PRY', '', 0, 1),
(167, '{\"en\":\"Peru\"}', 'PE', 'PER', '', 0, 1),
(168, '{\"en\":\"Philippines\"}', 'PH', 'PHL', '', 0, 1),
(169, '{\"en\":\"Pitcairn\"}', 'PN', 'PCN', '', 0, 1),
(170, '{\"en\":\"Poland\"}', 'PL', 'POL', '', 0, 1),
(171, '{\"en\":\"Portugal\"}', 'PT', 'PRT', '', 0, 1),
(172, '{\"en\":\"Puerto Rico\"}', 'PR', 'PRI', '', 0, 1),
(173, '{\"en\":\"Qatar\"}', 'QA', 'QAT', '', 0, 1),
(174, '{\"en\":\"Reunion\"}', 'RE', 'REU', '', 0, 1),
(175, '{\"en\":\"Romania\"}', 'RO', 'ROM', '', 0, 1),
(176, '{\"en\":\"Russian Federation\"}', 'RU', 'RUS', '', 0, 1),
(177, '{\"en\":\"Rwanda\"}', 'RW', 'RWA', '', 0, 1),
(178, '{\"en\":\"Saint Kitts and Nevis\"}', 'KN', 'KNA', '', 0, 1),
(179, '{\"en\":\"Saint Lucia\"}', 'LC', 'LCA', '', 0, 1),
(180, '{\"en\":\"Saint Vincent and the Grenadines\"}', 'VC', 'VCT', '', 0, 1),
(181, '{\"en\":\"Samoa\"}', 'WS', 'WSM', '', 0, 1),
(182, '{\"en\":\"San Marino\"}', 'SM', 'SMR', '', 0, 1),
(183, '{\"en\":\"Sao Tome and Principe\"}', 'ST', 'STP', '', 0, 1),
(184, '{\"en\":\"Saudi Arabia\"}', 'SA', 'SAU', '', 0, 1),
(185, '{\"en\":\"Senegal\"}', 'SN', 'SEN', '', 0, 1),
(186, '{\"en\":\"Seychelles\"}', 'SC', 'SYC', '', 0, 1),
(187, '{\"en\":\"Sierra Leone\"}', 'SL', 'SLE', '', 0, 1),
(188, '{\"en\":\"Singapore\"}', 'SG', 'SGP', '', 0, 1),
(189, '{\"en\":\"Slovak Republic\"}', 'SK', 'SVK', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city} {postcode}\r\n{zone}\r\n{country}', 0, 1),
(190, '{\"en\":\"Slovenia\"}', 'SI', 'SVN', '', 0, 1),
(191, '{\"en\":\"Solomon Islands\"}', 'SB', 'SLB', '', 0, 1),
(192, '{\"en\":\"Somalia\"}', 'SO', 'SOM', '', 0, 1),
(193, '{\"en\":\"South Africa\"}', 'ZA', 'ZAF', '', 0, 1),
(194, '{\"en\":\"South Georgia & South Sandwich Islands\"}', 'GS', 'SGS', '', 0, 1),
(195, '{\"en\":\"Spain\"}', 'ES', 'ESP', '', 0, 1),
(196, '{\"en\":\"Sri Lanka\"}', 'LK', 'LKA', '', 0, 1),
(197, '{\"en\":\"St. Helena\"}', 'SH', 'SHN', '', 0, 1),
(198, '{\"en\":\"St. Pierre and Miquelon\"}', 'PM', 'SPM', '', 0, 1),
(199, '{\"en\":\"Sudan\"}', 'SD', 'SDN', '', 0, 1),
(200, '{\"en\":\"Suriname\"}', 'SR', 'SUR', '', 0, 1),
(201, '{\"en\":\"Svalbard and Jan Mayen Islands\"}', 'SJ', 'SJM', '', 0, 1),
(202, '{\"en\":\"Swaziland\"}', 'SZ', 'SWZ', '', 0, 1),
(203, '{\"en\":\"Sweden\"}', 'SE', 'SWE', '{company}\r\n{firstname} {lastname}\r\n{address_1}\r\n{address_2}\r\n{postcode} {city}\r\n{country}', 1, 1),
(204, '{\"en\":\"Switzerland\"}', 'CH', 'CHE', '', 0, 1),
(205, '{\"en\":\"Syrian Arab Republic\"}', 'SY', 'SYR', '', 0, 1),
(206, '{\"en\":\"Taiwan\"}', 'TW', 'TWN', '', 0, 1),
(207, '{\"en\":\"Tajikistan\"}', 'TJ', 'TJK', '', 0, 1),
(208, '{\"en\":\"Tanzania, United Republic of\"}', 'TZ', 'TZA', '', 0, 1),
(209, '{\"en\":\"Thailand\"}', 'TH', 'THA', '', 0, 1),
(210, '{\"en\":\"Togo\"}', 'TG', 'TGO', '', 0, 1),
(211, '{\"en\":\"Tokelau\"}', 'TK', 'TKL', '', 0, 1),
(212, '{\"en\":\"Tonga\"}', 'TO', 'TON', '', 0, 1),
(213, '{\"en\":\"Trinidad and Tobago\"}', 'TT', 'TTO', '', 0, 1),
(214, '{\"en\":\"Tunisia\"}', 'TN', 'TUN', '', 0, 1),
(215, '{\"en\":\"Turkey\"}', 'TR', 'TUR', '', 0, 1),
(216, '{\"en\":\"Turkmenistan\"}', 'TM', 'TKM', '', 0, 1),
(217, '{\"en\":\"Turks and Caicos Islands\"}', 'TC', 'TCA', '', 0, 1),
(218, '{\"en\":\"Tuvalu\"}', 'TV', 'TUV', '', 0, 1),
(219, '{\"en\":\"Uganda\"}', 'UG', 'UGA', '', 0, 1),
(220, '{\"en\":\"Ukraine\"}', 'UA', 'UKR', '', 0, 1),
(221, '{\"en\":\"United Arab Emirates\"}', 'AE', 'ARE', '', 0, 1),
(222, '{\"en\":\"United Kingdom\"}', 'GB', 'GBR', '', 1, 1),
(223, '{\"en\":\"United States\"}', 'US', 'USA', '{firstname} {lastname}\r\n{company}\r\n{address_1}\r\n{address_2}\r\n{city}, {zone} {postcode}\r\n{country}', 0, 1),
(224, '{\"en\":\"United States Minor Outlying Islands\"}', 'UM', 'UMI', '', 0, 1),
(225, '{\"en\":\"Uruguay\"}', 'UY', 'URY', '', 0, 1),
(226, '{\"en\":\"Uzbekistan\"}', 'UZ', 'UZB', '', 0, 1),
(227, '{\"en\":\"Vanuatu\"}', 'VU', 'VUT', '', 0, 1),
(228, '{\"en\":\"Vatican City State (Holy See)\"}', 'VA', 'VAT', '', 0, 1),
(229, '{\"en\":\"Venezuela\"}', 'VE', 'VEN', '', 0, 1),
(230, '{\"en\":\"Viet Nam\"}', 'VN', 'VNM', '', 0, 1),
(231, '{\"en\":\"Virgin Islands (British)\"}', 'VG', 'VGB', '', 0, 1),
(232, '{\"en\":\"Virgin Islands (U.S.)\"}', 'VI', 'VIR', '', 0, 1),
(233, '{\"en\":\"Wallis and Futuna Islands\"}', 'WF', 'WLF', '', 0, 1),
(234, '{\"en\":\"Western Sahara\"}', 'EH', 'ESH', '', 0, 1),
(235, '{\"en\":\"Yemen\"}', 'YE', 'YEM', '', 0, 1),
(237, '{\"en\":\"Democratic Republic of Congo\"}', 'CD', 'COD', '', 0, 1),
(238, '{\"en\":\"Zambia\"}', 'ZM', 'ZMB', '', 0, 1),
(239, '{\"en\":\"Zimbabwe\"}', 'ZW', 'ZWE', '', 0, 1),
(242, '{\"en\":\"Montenegro\"}', 'ME', 'MNE', '', 0, 1),
(243, '{\"en\":\"Serbia\"}', 'RS', 'SRB', '', 0, 1),
(244, '{\"en\":\"Aaland Islands\"}', 'AX', 'ALA', '', 0, 1),
(245, '{\"en\":\"Bonaire, Sint Eustatius and Saba\"}', 'BQ', 'BES', '', 0, 1),
(246, '{\"en\":\"Curacao\"}', 'CW', 'CUW', '', 0, 1),
(247, '{\"en\":\"Palestinian Territory, Occupied\"}', 'PS', 'PSE', '', 0, 1),
(248, '{\"en\":\"South Sudan\"}', 'SS', 'SSD', '', 0, 1),
(249, '{\"en\":\"St. Barthelemy\"}', 'BL', 'BLM', '', 0, 1),
(250, '{\"en\":\"St. Martin (French part)\"}', 'MF', 'MAF', '', 0, 1),
(251, '{\"en\":\"Canary Islands\"}', 'IC', 'ICA', '', 0, 1),
(252, '{\"en\":\"Ascension Island (British)\"}', 'AC', 'ASC', '', 0, 1),
(253, '{\"en\":\"Kosovo, Republic of\"}', 'XK', 'UNK', '', 0, 1),
(254, '{\"en\":\"Isle of Man\"}', 'IM', 'IMN', '', 0, 1),
(255, '{\"en\":\"Tristan da Cunha\"}', 'TA', 'SHN', '', 0, 1),
(256, '{\"en\":\"Guernsey\"}', 'GG', 'GGY', '', 0, 1),
(257, '{\"en\":\"Jersey\"}', 'JE', 'JEY', '', 0, 1);
